name: Adiciona latitude e longitude nos arquivos de cep

on:
  schedule:
    - cron: "0 00 * * 1-5"
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium==4.33.0
        pip install geopy==2.4.1
        pip install beautifulsoup4==4.13.4

    - name: Run Python script
      run: python adiciona_coordenadas.py
      
    - name: Commit and push updated last date
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git pull origin main
        git add --all
        git commit -m "Coordenadas adicionadas!"
        git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} HEAD:main
